### ISSUE TITLE
Possible Interpreter stack problem with JSON arrays

### ISSUE THREAD

**Issue by xcrover** [atifaziz/JSONPath#11]
Hello Guys,
Thank you for this piece of code.
I am trying to use it for pet project and found that Interpreter stack is misbehaving on the JSON like this:
```JSON
[
  {
	"key": "k1",
	"value": "N1"
  },
  {
	"key": "k2",
	"value": "N2"
  },
  {
	"key": "k3",
	"value": "N3"
  }
]
```

It seems that the Interpreter does not like array as a root when Json Path is "$.[*]"

**Comment by atifaziz** [comment]
What's the output you expect? What are you actually getting?

**Comment by atifaziz** [comment]
Closing this due to lack of response.

**Comment by xcrover** [comment]
Sorry Aziz,

Your Email got into the junk folder on my side, noticed too late.

Here is the thing:
If I try to traverse the above JSON with path "$.[*]" I first get list of three objects {key, value} and after that all the field values one-by-one.
I would expect to get just three objects  {key, value} .

Btw, I found that "$.*" works as expected, i.e. returns three objects.

If I use structure
```JSON
{
  "values" : [
   ...
  ]
}
```
and JSON Path "$.values[*]" then I get three objects, as expected.

So it seems that "$.[*]" works differently than "$.values[*]" for similar source.

**Comment by atifaziz** [comment]
You should either use `$[*]` or `$.*` but not both. Per JSONPath, `.` and `[]` mean _child operation_. This implementation works like some other and yet [not all behave the same](https://cburgmer.github.io/json-path-comparison/). At <https://jsonpath.com>, you'll find the result is the same.

**Comment by xcrover** [comment]
OK, thank you.
As long as I can get the data properly, it works for me.
Just did not expect that there will be such difference between `$.values[*]` and `$.[*]`.
