### ISSUE TITLE
Question: Do you support any form filter "and" logic?

### ISSUE THREAD

**Issue by NigelThorne** [atifaziz/JSONPath#3]
as per https://stackoverflow.com/questions/29703891/jsonpath-and-operator-on-array

I have a need to apply a filter xxx[?(@.MessageType=="a")].SomeProperty  
But there are multiple matches... so I want the last one.

in JSON.Net I tried a few things but the indexing support is dodgy :)

I'm looking for xxx[?(@.MessageType=="a") && -1: ].SomeProperty  or something like that. .. 

Can I achieve that behaviour with your implementation? 

Cheers
Nigel

**Comment by atifaziz** [comment]
> Can I achieve that behaviour with your implementation?

Not directly. The `?()` syntax in JSONPath relies on _some scripting expression_ for more complex criteria. While JSONPath doesn't define a specific scripting language, most examples of scripting are usually in JavaScript. My implementation lets you plug in an evaluation function for those expressions. I've added a test (see 298af9cd4eb16ca0d44dac85bbea071102491305 and below) to show how you can use the [Jint](https://github.com/sebastienros/jint) project (a Javascript interpreter for .NET) to bring in JavaScript evaluation:

https://github.com/atifaziz/JSONPath/blob/298af9cd4eb16ca0d44dac85bbea071102491305/tests/SelectionTests.cs#L297-L312

You can also imagine using C# scripting.

**Comment by NigelThorne** [comment]
Ah I see .. I understand more now. Thanks for that.
