### ISSUE TITLE
How to implement the "ScriptEvaluator" method?

### ISSUE THREAD

**Issue by NigelThorne** [atifaziz/JSONPath#6]
The default implementation returns null. What would be valid data structures for this method to return? 

_eval is called in two scenarios:- 
* `[(exp)]` - this call to _eval seems to be expecting a node back... but I'm not sure.
* `[?(exp)]` - this call to _eval seems to want a bool back. 

This doesn't seem possible.  What am I not getting?

Cheers
Nigel

**Comment by atifaziz** [comment]
See #3 where we already discussed this and I shared an example implementation.
